apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oss-risk-radar

resources:
- namespace.yaml
- app-config.yaml
- postgres.yaml
- scoring.yaml
- api.yaml
- web.yaml
- ingress.yaml

configMapGenerator:
- files:
  - postgres-init/001_initial_schema.sql
  name: postgres-init

generatorOptions:
  disableNameSuffixHash: true

images:
- name: ghcr.io/esuarken/oss-risk-radar-api
  newName: ghcr.io/esuarken/oss-risk-radar-api
  newTag: a830c38687f6d0a4cc58aa9758d91760e01c18ba
- name: ghcr.io/esuarken/oss-risk-radar-scoring
  newName: ghcr.io/esuarken/oss-risk-radar-scoring
  newTag: a830c38687f6d0a4cc58aa9758d91760e01c18ba
- name: ghcr.io/esuarken/oss-risk-radar-web
  newName: ghcr.io/esuarken/oss-risk-radar-web
  newTag: a830c38687f6d0a4cc58aa9758d91760e01c18ba

replacements:
- source:
    fieldPath: data.PUBLIC_HOST
    kind: ConfigMap
    name: oss-risk-radar-config
  targets:
  - fieldPaths:
    - spec.rules.0.host
    - spec.tls.0.hosts.0
    select:
      kind: Ingress
      name: oss-risk-radar
