version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/deployment/docker"
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: "/backend/api"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/mltraining/scoring"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
